<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><DebugType>portable</DebugType></PropertyGroup><ItemGroup><PackageReference Include="EntityFramework" Version="6.4.4" /></ItemGroup><ItemGroup><ProjectReference Include="..\Database\Database.csproj" /></ItemGroup></Project>